name: rassi_assist
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.4+114

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  http: ^1.1.2
  firebase_core: ^2.25.4
  firebase_analytics: ^10.8.6
  firebase_messaging: ^14.7.16
  firebase_in_app_messaging: ^0.7.4+14
  firebase_remote_config: ^4.3.14
  firebase_dynamic_links: ^5.4.14
  firebase_auth: ^4.3.0
  firebase_crashlytics: ^3.4.15
  google_fonts: ^4.0.1
  shared_preferences: ^2.2.2
  provider: ^6.0.4
  intl: ^0.18.1
  fluttertoast: ^8.1.1
  uuid: ^3.0.7
  flutter_local_notifications: ^13.0.0
  in_app_purchase: ^3.0.7
  in_app_purchase_storekit: ^0.3.4
  flutter_inapp_purchase: ^5.3.1
  card_swiper: ^3.0.1
  url_launcher: ^6.1.7
  webview_flutter: ^2.0.4
  flutter_inappwebview: ^5.8.0
  flutter_html: ^3.0.0-beta.2
  flutter_html_table: ^3.0.0-beta.2
  cupertino_will_pop_scope: ^1.2.1
  gif: ^2.3.0
  auto_size_text: ^3.0.0

  cross_scroll: ^0.0.76
  cached_network_image: ^3.3.1
  pull_to_refresh: ^2.0.0
  modal_bottom_sheet: ^2.0.1
  lottie: ^3.0.0
  logger: ^1.1.0

  device_info_plus: ^8.0.0
  shimmer: ^2.0.0
  skeleton_loader: ^2.0.0+4
  app_tracking_transparency: ^2.0.4
  #  facebook_app_events: ^0.19.0
  table_sticky_headers: ^2.0.5
  dotted_line: ^3.1.0
  another_xlider: ^1.1.2
  timeline_tile: ^2.0.0
  speech_balloon: ^0.0.4
  flutter_keyboard_visibility: ^5.4.1
  visibility_detector: ^0.4.0+2
  month_picker_dialog: ^2.4.0
  flutter_localization: ^0.2.0
  dropdown_button2: ^2.1.4
  animated_flip_counter: ^0.2.6
  flutter_native_splash: ^2.2.9
  #google_tag_manager: ^0.1.0
  #js: ^0.6.3


  #차트
  fl_chart: ^0.60.0
  flutter_echarts: ^2.3.0
  syncfusion_flutter_charts: ^24.2.8

  #간편로그인
  kakao_flutter_sdk: ^1.2.2
  flutter_naver_login: ^1.7.0
  sign_in_with_apple: ^5.0.0
#  apple_sign_in_safety: ^0.0.6
  google_sign_in: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - images/
    - assets/

  uses-material-design: true

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
    - family: Godo
      fonts:
        - asset: assets/fonts/GodoB.ttf
  #  - family: TrainOne
  #    fonts:
  #      - asset: assets/fonts/TrainOne-Regular.ttf
  #        weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages